# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Stephan Brandauer
#email: none@available.com
description: > # this means to ignore newlines until "baseurl:"
  Programming languages and types.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kaeluka.github.io" # the base hostname & protocol for your site
twitter_username: sbrandauer
github_username:  kaeluka
linkedin_username:  stephan-brandauer
instagram_username:  kaelukaphotos

# Build settings
markdown: kramdown
